version: 2
jobs:
  build:
    docker:
      # A debian image with node 10 and docker cli
      - image: erulabs/circleci-builder:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
          version: 17.06.1-ce

      - run:
          name: Integration testing...
          command: ./.circleci/e2e_wrapper.sh ci

      - run:
          name: Cleaning up!
          command: ./bin/clean.sh hard

workflows:
  version: 2
  build:
    jobs:
      - build
