version: 2
jobs:
  build:
    docker:
      # A debian image with node 10 and docker cli
      - image: erulabs/circleci-builder:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
          version: 17.06.1-ce

      - restore_cache:
          keys:
          - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}

      # Test wrapper - all unit / static / lint tests should occur here
      - run:
          name: Unit testing...
          command: |
            chmod +x ./bin/*.sh
            chmod +x ./.circleci/*.sh
            ./bin/lint.sh
            ./bin/unit_test.sh

      - run:
          name: Integration testing...
          command: ./.circleci/e2e_wrapper.sh ci

      - run:
          name: Cleaning up!
          command: ./bin/clean.sh hard

workflows:
  version: 2
  build:
    jobs:
      - build
